#cloud-config
package_update: true
package_upgrade: true
package_reboot_if_required: true

apt_sources:
  - source: "ppa:git-core/ppa"

packages:
  - curl
  - python3
  - python3-dev
  - python3-pip
  - wget

write_files:
  - owner: root:root
    path: /opt/testfile.txt
    content: |
      "Hello world"

runcmd:
  - [sh, -xc, echo, "Test"]

power_state:
  delay: "+5"
  mode: reboot
  message: Reboot after configuration finishes.
  timeout: 30
  condition: true
